#include<iostream>
#include<string.h>
using namespace std;
char * bill_cipher (char * argv){
  int n = strlen(argv);
  char *result = new char[n+1];
  for (int i =0 ; i<n ; i++){
    result[i]=argv[i]^0x32;
  }
  result[n]='\n';
  return result;
}
int main (int argc, char *argv[])
{
  short  cipher[] = {0x51,0x46,0x54,0x49,0x0a,0x5b,0x03,0x03,0x6d,0x03,0x02,0x6d,0x44,0x01,0x6d,0x46,0x02,0x56,0x02,0x4f,0x0a};
  char * flag = bill_cipher(argv[1]);
  for (int i=0;i<strlen(flag); i++){
    if (cipher[i]!=flag[i]){
      printf("All meco this vato\n");
      exit(0);

    }
  }
printf("\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX00000O0000XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo..........oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl .d0000d. lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl '0MMMM0' lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl 'OMMMMO' lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl 'OMMMM0' lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl '0MMMM0' lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl 'OMMMM0' lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0l::.  ,::::,  .::l0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0l::::.      .:c::l0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk' ,oo, 'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx. :KMWK: .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo..lXMMMMXl..oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl..oNMMMMMMNo..cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK: .xWMMMMMMMMWx. :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0, 'OWMMMMMMMMMMWO' ,0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk' ;OX0kdollllodk0XO; 'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx. 'c:'...'.  .'...':c' .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.   .,lk0XO,  ,OX0kl,.   .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc   .:ONMMMNl    lNMMMNO:.   cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:   .xNMMMMMK,    ,KMMMMMNx.   :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0, .. ,0MMMMMM0'    '0MMMMMM0, .. ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk' ;OO, 'xNMMMMX:    :XMMMMNk' ,O0; 'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx. cKMMXo..,d0NWWO.  .kWWN0d,..oXMMKc .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMWMMMMMMMMMMMMMMNo..lXMMMMWKd;..';cc'  'cc;'..;dKWMMMMXl..oNMMMMMMMMMMMMMMWMMMMMMMMMMMMM\n\
MMMMMMMMMMMXo:xNMMMMMMMMMMMXc..dNMMMMMMMMWKxo:;,'..',;:oxKWMMMMMMMMNd. cXMMMMMMMMMMMNx:oXMMMMMMMMMMM\n\
MMMMMMMMMMMNd..;xXWMMMMMMMK; .xWMMMMMMMMMMMMMMWWNNNNWWMMMMMMMMMMMMMMWx. :KMMMMMMMWXx;..dNMMMMMMMMMMM\n\
MMMMMMMMMMMMW0l...cdOKNWWO, ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO, ,OWWNXOdc'..l0WMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMWXxc,...',;. ,llkWWklkWWklkWWklkWWkllkWWklkWWklkWWklkWWkll, .;,'...,cxXWMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMNKOxl.  c0klkWWklkWWkckWWklkWWkllkWWklkWWkckWWklkWWklk0c  .cxOKNMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMNo..lXMMMMMMMMMMWx:xWMMMMMMMMMMMMMMMMWx:xWMMMMMMMMMMNl..oNMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMXc .oNMMWWWMMWWWMWOlOWMWWWMMWWWWMMWWWMWOlOWMWWWMMWWWMMNo. cXMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMM0; .',xWWx;xWWx;xWWx;xWWx;xWWx;;xWWx;xWWx;xWWx;xWWx;xWWx,'. ;KWMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMWO, ,k0x0WWOoOWW0x0WW0x0WW0x0WWOooOWW0x0WW0x0WW0x0WWOoOWW0x0k, ,OWMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMWk. ;0MMMMMNd,dWMMMMMMMMMMMMMMMWd,,dNMMMMMMMMMMMMMMMWd,dWMMMMM0; .kWMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMNd. 'd00000OOdldO000000000000000OdlldOO00000000000000OdldO000000d' .dNMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMNd.  ................... ........................ .................  .dNMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMWK000000000O0000000000d. ,k0000000000000O000000x' 'x000000000000000000KWMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..dWMMMMMMMMMMMMMMMMMM MMNl .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl '0MMMMMMMMMMMMMMMMMMMMMMx..dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMWXOOKXWMK, :XMMMMMMMMMMMMMMMMMMMMMMK, :XWXOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMWd'...,:, .dWMMMMMMMMMMMMMMMMMMMMMMNl .,,..'dWMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOkdl:,'cKMMMMMMMMMMMMMMMMMMMMMMMMO;';ldkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n");
printf("Excelente mi niño ahora ¿¿¿sabes la clave para vencer a Bill Cipher???\n");
string clave2 = ""; 
cin>>clave2;
if (clave2.length()!=0x05){
  printf("Provocaste el RAROMAGEDON suerte para la proxima\n");exit(0);
  }
if ((clave2[0x00]^0x20)=='M' && (clave2[0x02]^0x20)=='B' && (clave2[0x01]^0x20)=='A'  && (clave2[0x04]^0x20)=='L' && (clave2[0x03]^0x20)=='E' ){
  printf("Parece que estas listo para las grandes ligas has salvado al mundo\n");
}else {
   printf("Provocaste el RAROMAGEDON suerte para la proxima\n");exit(0);
}
  return 0;
}
